# Generated by Django 4.2.5 on 2023-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name=' Name ')),
                ('email', models.EmailField(max_length=225, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('messages', models.TextField(max_length=225, null=True, verbose_name='Mesagges')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=225, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=225, verbose_name='ism , familiya')),
                ('teacher', models.CharField(max_length=225, verbose_name='Mavzu')),
                ('messages', models.TextField(max_length=225, null=True, verbose_name='Mesagges')),
                ('number', models.CharField(max_length=225, verbose_name='Telefon nomer')),
            ],
        ),
    ]
